### ISSUE TITLE
[LIVESTREAM!] Celtics vs Mavericks LIVE Free NBA Final Game 3 ON TV Channel 6/12/24

### ISSUE THREAD

**Issue by ghost** [foundation/motion-ui#1868]
How to watch Mavericks vs. Celtics basketball game. The Boston Celtics visit the Dallas Mavericks in Game 3 of the 2024 NBA Finals on Wednesday, June 12, 2024 (6/12/24) at American Airlines Center in Dallas, Texas.

**[CLICK HERE TO GET NOW FREE](https://appbitly.com/Live-Stream)**

How To Watch
When: Wednesday, June 12, 2024 at 8:30 p.m. ET
Where: American Airlines Center -- Dallas, Texas
TV: ABC
Follow: CBS Sports App
Online streaming: fuboTV (Try for free. Regional restrictions may apply.)
Ticket Cost: $114.24

After three games on the road, the Mavericks are heading back home. They and the Boston Celtics will meet in Dallas for Game 3 of the NBA Finals at 8:30 p.m. ET on Wednesday at American Airlines Center. The Mavericks are the slight favorite, but fans should be in for an exciting game likely to go down to the wire.

The Mavericks are headed into this one after the oddsmakers set last week's over/under low at 215, but even that wound up being too high. They took a 105-98 hit to the loss column at the hands of the Celtics on Sunday. The loss unfortunately continues a disappointing trend for Dallas in their matchups with Boston: they've now lost six in a row.

Luka Doncic put forth a good effort for the losing side as he dropped a triple-double on 32 points, 11 rebounds, and 11 assists. His evening made it nine games in a row in which he has scored at least 30 points.

The Mavericks are sitting on shaky ground at the moment, as the Celtics currently lead the series 2-0. Come back after the game to see if the Mavericks change their momentum or if the Celtics keep theirs going.

**Comment by Rayma4bristy** [comment]
### 📺📱 [Boston Celtics vs Dallas Mavericks](https://www.onflix.online/nba.php)

### 📺📱 [CLICK HERE COVERAGE ](https://t.co/9DWGJom7TD)

.

[![LiveStream](https://go4s.wordpress.com/wp-content/uploads/2024/05/livestream.png)](https://t.co/lVoqEQosqJ)

➭

### 📺📱 [Boston Celtics vs Dallas Mavericks](https://www.onflix.online/nba.php)

### 📺📱 [Boston Celtics vs Dallas Mavericks](https://t.co/9DWGJom7TD)

.

[![LiveStream](https://go4s.wordpress.com/wp-content/uploads/2024/05/livestream.png)](https://t.co/lVoqEQosqJ)

➭

### 📺📱 [Boston Celtics vs Dallas Mavericks](https://www.onflix.online/nba.php)

### 📺📱 [CLICK HERE COVERAGE ](https://t.co/9DWGJom7TD)

.

[![LiveStream](https://go4s.wordpress.com/wp-content/uploads/2024/05/livestream.png)](https://t.co/lVoqEQosqJ)

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭


➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭

➭
